---
name: Build and Push

on:
  pull_request:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '10 6,15 * * *'
  workflow_dispatch:

jobs:
  # If on main branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set short
        run: echo "short=${GITHUB_REF##*/}" >> "${GITHUB_ENV}"
      - name: Set tag
        run: echo "tag=${short/master/latest}" >> "${GITHUB_ENV}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            buluma/fedora-systemd:42, buluma/fedora-systemd:latest
