---
name: Build and Push

on:
  pull_request:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '10 6,15 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  # test:
  #   name: Test Fedora-main
  #   # runs-on: ubuntu-latest
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-20.04]
  #
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - name: Test building image.
  #       run: docker build -t docker-fedora-main .
  #
  #     - name: Run the built image.
  #       run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-fedora-main

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: /
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            buluma/fedora-systemd:38, buluma/fedora-systemd:latest
