---
name: Build and Push

on:
  pull_request:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '10 6,15 * * *'
  workflow_dispatch:

jobs:
  # If on main branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: /
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            buluma/fedora-systemd:38
